In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
df = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [3]:
df.select_dtypes(["object"]).describe()

            species
count           990
unique           99
top     Acer_Opalus
freq             10

In [4]:
df = df.drop(columns=["species"])

In [5]:
df.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 193 columns):
 #    Column     Dtype
---   ------     -----
 0    id         int64
 1    margin1    float64
 2    margin2    float64
 3    margin3    float64
 4    margin4    float64
 5    margin5    float64
 6    margin6    float64
 7    margin7    float64
 8    margin8    float64
 9    margin9    float64
 10   margin10   float64
 11   margin11   float64
 12   margin12   float64
 13   margin13   float64
 14   margin14   float64
 15   margin15   float64
 16   margin16   float64
 17   margin17   float64
 18   margin18   float64
 19   margin19   float64
 20   margin20   float64
 21   margin21   float64
 22   margin22   float64
 23   margin23   float64
 24   margin24   float64
 25   margin25   float64
 26   margin26   float64
 27   margin27   float64
 28   margin28   float64
 29   margin29   float64
 30   margin30   float64
 31   margin31   float64
 32   margin32   float64
 33   margin33   float64
 34   margin34   float64
 35   margin35   float64
 36   margin36   float64
 37   margin37   float64
 38   margin38   float64
 39   margin39   float64
 40   margin40   float64
 41   margin41   float64
 42   margin42   float64
 43   margin43   float64
 44   margin44   float64
 45   margin45   float64
 46   margin46   float64
 47   margin47   float64
 48   margin48   float64
 49   margin49   float64
 50   margin50   float64
 51   margin51   float64
 52   margin52   float64
 53   margin53   float64
 54   margin54   float64
 55   margin55   float64
 56   margin56   float64
 57   margin57   float64
 58   margin58   float64
 59   margin59   float64
 60   margin60   float64
 61   margin61   float64
 62   margin62   float64
 63   margin63   float64
 64   margin64   float64
 65   shape1     float64
 66   shape2     float64
 67   shape3     float64
 68   shape4     float64
 69   shape5     float64
 70   shape6     float64
 71   shape7     float64
 72   shape8     float64
 73   shape9     float64
 74   shape10    float64
 75   shape11    float64
 76   shape12    float64
 77   shape13    float64
 78   shape14    float64
 79   shape15    float64
 80   shape16    float64
 81   shape17    float64
 82   shape18    float64
 83   shape19    float64
 84   shape20    float64
 85   shape21    float64
 86   shape22    float64
 87   shape23    float64
 88   shape24    float64
 89   shape25    float64
 90   shape26    float64
 91   shape27    float64
 92   shape28    float64
 93   shape29    float64
 94   shape30    float64
 95   shape31    float64
 96   shape32    float64
 97   shape33    float64
 98   shape34    float64
 99   shape35    float64
 100  shape36    float64
 101  shape37    float64
 102  shape38    float64
 103  shape39    float64
 104  shape40    float64
 105  shape41    float64
 106  shape42    float64
 107  shape43    float64
 108  shape44    float64
 109  shape45    float64
 110  shape46    float64
 111  shape47    float64
 112  shape48    float64
 113  shape49    float64
 114  shape50    float64
 115  shape51    float64
 116  shape52    float64
 117  shape53    float64
 118  shape54    float64
 119  shape55    float64
 120  shape56    float64
 121  shape57    float64
 122  shape58    float64
 123  shape59    float64
 124  shape60    float64
 125  shape61    float64
 126  shape62    float64
 127  shape63    float64
 128  shape64    float64
 129  texture1   float64
 130  texture2   float64
 131  texture3   float64
 132  texture4   float64
 133  texture5   float64
 134  texture6   float64
 135  texture7   float64
 136  texture8   float64
 137  texture9   float64
 138  texture10  float64
 139  texture11  float64
 140  texture12  float64
 141  texture13  float64
 142  texture14  float64
 143  texture15  float64
 144  texture16  float64
 145  texture17  float64
 146  texture18  float64
 147  texture19  float64
 148  texture20  float64
 149  texture21  float64
 150  texture22  float64
 151  texture23  float64
 152  texture24  float64
 153  texture25  float64
 154  texture26  float64
 155  texture27  float64
 156  texture28  float64
 157  texture29  float64
 158  texture30  float64
 159  texture31  float64
 160  texture32  float64
 161  texture33  float64
 162  texture34  float64
 163  texture35  float64
 164  texture36  float64
 165  texture37  float64
 166  texture38  float64
 167  texture39  float64
 168  texture40  float64
 169  texture41  float64
 170  texture42  float64
 171  texture43  float64
 172  texture44  float64
 173  texture45  float64
 174  texture46  float64
 175  texture47  float64
 176  texture48  float64
 177  texture49  float64
 178  texture50  float64
 179  texture51  float64
 180  texture52  float64
 181  texture53  float64
 182  texture54  float64
 183  texture55  float64
 184  texture56  float64
 185  texture57  float64
 186  texture58  float64
 187  texture59  float64
 188  texture60  float64
 189  texture61  float64
 190  texture62  float64
 191  texture63  float64
 192  texture64  float64
dtypes: float64(192), int64(1)
memory usage: 1.5 MB

In [6]:
df.isna().sum().sort_values(ascending=True)

id           0
shape58      0
shape59      0
shape60      0
shape61      0
            ..
shape3       0
shape4       0
shape5       0
shape31      0
texture64    0
Length: 193, dtype: int64

In [7]:
df_corr = df.corr()
high_corr = df_corr[(df_corr > .85) & ~(df_corr == 1)]

In [ ]:
# for col in df.columns:
#     col_high_corr = high_corr[col][high_corr[col] > 0]
#     for index in col_high_corr.index:
#         plt.figure()
#         sns.scatterplot(x= index, y= col, data= df)
#         plt.xlabel(index)
#         plt.ylabel(col)
#         plt.title(f"corr between {col} & {index} = {col_high_corr[index]}")

In [8]:
df_corr["shape64"]

id           0.015805
margin1     -0.110691
margin2     -0.092298
margin3     -0.065155
margin4     -0.006535
               ...
texture60   -0.096818
texture61   -0.173204
texture62   -0.012569
texture63    0.024816
texture64    0.038334
Name: shape64, Length: 193, dtype: float64